/*! Generated by poi~ language | (c) 2015-2016, poi~ dev group | poi_lang@pku.edu.cn */
var __poi_temp_variable, __poi_temp_struct;
var __poi_temp_return = new Array();
var __poi_cnt = 0;

function Event() {
    this.NamedKeys = new Object();
    this.NamedFunctions = new Array();
    this.AnonymousFunctions = new Array();

    this.add = function (key, value) {
        if (key == "") {
            this.AnonymousFunctions.push(value);
        }
        else {
            var current = this.NamedFunctions.length;
            this.NamedKeys[key] = current;
            this.NamedFunctions.push(value);
        }
    }

    this.remove = function (key) {
        if (typeof (this.NamedKeys[key]) == "number") {
            var index = this.NamedKeys[key];
            this.NamedFunctions.splice(index, 1);
        }
    }

    this.execute = function () {
        var paraNumber = arguments.length;
        for (i = 0; i < this.NamedFunctions.length; i++) {
            this.NamedFunctions[i].apply(null, arguments);
        }
        for (i = 0; i < this.AnonymousFunctions.length; i++) {
            this.AnonymousFunctions[i].apply(null, arguments);
        }
    }
};

function __poi_ajax_request(method, url, data, cors, resp_succ, resp_err, extra_config) {
    var config = {
        method: method,
        url: url,
        data: data,
        success: function (data) { resp_succ.execute(data); },
        error: function (xhr, err) { resp_err.execute.call(xhr, err); }
    };
    for (var key in extra_config) {
        config[key] = extra_config[key];
    }
    if (cors) config.xhrFields.withCredentials = true;
    $.ajax(config);
}
var __poi_ajax = new Event();
__poi_ajax.add('', __poi_ajax_request);
